### ISSUE TITLE
Proper error message be thrown while trying to rename a tenant with an existing tenant's name

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1093]
Steps:
1. Create two tenants.
2. Rename a tenant with an existing tenant's name - see a big stacktrace on the esx's console.
    Error message should be clear to the user.

-----

Steps and their output are as follows:

1. Created two tenants - user_tenant1 and user_tenant_2

```
[root@sc-rdops-vm02-dhcp-34-69:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vm-group create --name=user_tenant_2
vm-group create succeeded
[root@sc-rdops-vm02-dhcp-34-69:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vm-group ls
Uuid                                  Name           Description                      Default_datastore  VM_list
------------------------------------  -------------  -------------------------------  -----------------  ------------
11111111-1111-1111-1111-111111111111  _DEFAULT       Renaming to old name - _DEFAULT
d5827a1e-4d7c-4e5f-913b-083582405b35  user_tenant1                                                       ubuntu-VM0.1
4ae2a634-98be-4053-9764-45a4b3605786  user_tenant_2

```

2. Tried to rename a tenant (user_tenant1) with an existing tenant's name (user_tenant_2)

```
[root@sc-rdops-vm02-dhcp-34-69:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vm-group update --name=user_tenant1 --description="Renaming tenant to an exiting tenant's name" --new-name=user_tenant_2
Traceback (most recent call last):
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 1042, in <module>
    main()
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 53, in main
    args.func(args)
  File "/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py", line 867, in tenant_update
    return operation_fail(error_info.msg)
AttributeError: 'tuple' object has no attribute 'msg'
```

Logs:
[vmdk_ops.txt](https://github.com/vmware/docker-volume-vsphere/files/871376/vmdk_ops.txt)

**Comment by govint** [comment]
Issue seems to be fixed in current code,

 /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup ls
Uuid                                  Name           Description                Default_datastore  VM_list
------------------------------------  -------------  -------------------------  -----------------  -------
11111111-1111-1111-1111-111111111111  _DEFAULT       This is a default vmgroup  _VM_DS
05c0d4b2-9066-4945-bdd4-50d91fe3a554  user_tenant_2                             _VM_DS
e180f3bf-9609-405a-ab93-735fed311a2c  user_tenant_1                             _VM_DS

/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vmgroup update --name=user_tenant_1 --description="Renaming tenant to an exiting tenant's name" --new-name=user_tenant_2
Vmgroup user_tenant_2 already exists
