### ISSUE TITLE
[Multi-ESX] Confusing difference in SingleNode vs MultiNode behavior after config init

### ISSUE THREAD

**Issue by ashahi1** [vmware/docker-volume-vsphere#1138]
Each time, after initializing SingleNode mode, vm-group ls will always initially list  _DEFAULT tenant unless user creates new tenant.
Whereas for MultiNode mode, after initializing MultiNode mode, vm-group ls may also show tenants other than _DEFAULT which might have been created from different ESXs. 
This can "may-be" create confusion for the user.

---------------------------------------------------------------------

Posted the output below to make things a bit clear.

- Configured SingleNode config on ESX-1 :
```
[root@sc-rdops-vm06-dhcp-162-163:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py config init --local
Creating new DB at /etc/vmware/vmdkops/auth-db
[root@sc-rdops-vm06-dhcp-162-163:~]

```
- Created a tenant
```
[root@sc-rdops-vm06-dhcp-162-163:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vm-group create --name=tenant_new
vm-group create succeeded
[root@sc-rdops-vm06-dhcp-162-163:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vm-group ls
Uuid                                  Name        Description                 Default_datastore  VM_list
------------------------------------  ----------  --------------------------  -----------------  -------
11111111-1111-1111-1111-111111111111  _DEFAULT    This is a default vm-group
f41a97dd-75d8-4591-9dea-132bc299e2da  tenant_new

```
- Removed SingleNode mode and I do not see the user created tenant
```
[root@sc-rdops-vm06-dhcp-162-163:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py config rm --local --confirm
Moved /etc/vmware/vmdkops/auth-db to backup file /etc/vmware/vmdkops/auth-db.bak_Sat_Apr__1_00:32:46_2017

```
- Again initialized SingleNode mode and vm-group ls only shows _DEFAULT tenant
```
[root@sc-rdops-vm06-dhcp-162-163:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vm-group ls
Uuid                                  Name      Description                 Default_datastore  VM_list
------------------------------------  --------  --------------------------  -----------------  -------
11111111-1111-1111-1111-111111111111  _DEFAULT  This is a default vm-group

```

--------------

After removing singleNode mode, initialized MutliNode mode and did admin-cli vm-group ls:

```
[root@sc-rdops-vm06-dhcp-162-163:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py config init --datastore=sharedVmfs-0
Creating a symlink to /vmfs/volumes/sharedVmfs-0/dockvols/vmdkops_config.db at /etc/vmware/vmdkops/auth-db
[root@sc-rdops-vm06-dhcp-162-163:~] /usr/lib/vmware/vmdkops/bin/vmdkops_admin.py vm-group ls
Uuid                                  Name          Description                        Default_datastore  VM_list
------------------------------------  ------------  ---------------------------------  -----------------  ------------
11111111-1111-1111-1111-111111111111  _DEFAULT      New description of default tenant
ed00d8a9-3709-4391-b7ed-333f0b5d41b1  new-vmgroup1  Hello from vmgroup1                vsanDatastore      VM1_163_vsan

```

I do see tenants other than _DEFAULT tenant which can confuse the user.

**Comment by msterin** [comment]
Related to #1065

**Comment by lipingxue** [comment]
@ashahi1 When do you create "new-vmgroup1"?

**Comment by ashahi1** [comment]
Had an offline discussion with Liping to explain what exactly is the issue here. 
Liping will have more discussion with Mark regarding this issue.

**Comment by msterin** [comment]
To clarify, this sequence of `config` commands has different results in SingleNode and MultiNode. 
* init
* modify (add vmgroups, whaterve)
* rm --local --confirm
* init again

On SingleNode, it produces new fresh config (as expected)
On MultiNode, it brings back the old config

The issue is that we **do not support** MultiNode **remove DB**, and `rm --local --confirm` command does not really rm the DB in this case, but instead, simply unlinks it.

So the fix here is to change command line semantic to reflect the above. Not that we are **NOT** changing the behavior which is by design, but changing commands to semantically match the behavior.

The change is as follows:
Choice 1: 
[ ] in MultiNode, `rm --local` command ONLY prints a message along this line (please changeappropriately)  "DB removed is not supported in MultiNode. Use `unlink` on each host and then manually rm the <db> file if needed".

[ ] New command `config unlink [--confirm]`. In MultiNode, it fully replaces current `rm --local`. In SingleNode, it suggest to use the rm

Choice 2:
[ ] rename 'rm' to 'unlink'
[ ] make sure unlink --local removes the DB and unlink with no local unlinks from shared (rm the link)

Choice 3
Something else

Please do a quick check with bystanders (Anup, Shaomin,etc..) to see which choice is more usable.

**Comment by ashahi1** [comment]
I like Choice 1: Use 'rm' in case of SingleNode mode and use 'unlink' in case of MultiNode mode.

**Comment by lipingxue** [comment]
@shaominchen What do you think? Which option is more reasonable for you?

**Comment by shaominchen** [comment]
Ideally we should have same/consistent command to support similar operations in different configurations. Even though today we don't support DB removal in MultiNode, that doesn't mean we will not support it in the future. So I would suggest this:

Choice 3:
[ ] In SingleNode, `rm --local` will remove the local DB. Same behavior as today. No code change.
[ ] In MultiNode, 'rm --remote' will print a message and remove the local symlink. The message can be something like "This operation will not remove remote DB. It will just remove the local symlink" . Same behavior as today, but just need to support a new "--remote" parameter.

In the future, if we decide to support removing shared DB (this is quite possible), we will simply remove above message, but the behavior will remain the same.

**Comment by lipingxue** [comment]
I think the choice 3 is good since it provides more flexibility to support possible future change. But the command ```rm --remote``` seems not accurate to me. How about ```rm --unlink```?
[ ]  In SingleNode, ```rm --local``` will remove the local DB, ```rm --unlink``` will return an error message to say this command is not supported in SingleNode configuration.

[ ] In MultiNode, ```rm --unlink``` will print a message and remove the local symlink. ```rm --local```  will return an error message to say ```rm --unlink``` is not support in MultiNode configuration.

**Comment by shaominchen** [comment]
I'm fine with "rm --unlink". Since "--unlink" is clear enough (for unlink operation), we don't even need to print the message. In the future if we need to support remote db removal, we can add a "rm --remote" option and deprecate "--unlink", or we may support both.

**Comment by msterin** [comment]
+1 from me on the latest suggestion.

**Comment by govint** [comment]
Just asking, why does the user need to remove the DB, would a "reset" option be sufficient to get the DB to a known initial state?

And can DB removal (for local nodes) be tied to VIB removal?
