### ISSUE TITLE
E2E test util verification.ExecCmd may cause the whole e2e test exit

### ISSUE THREAD

**Issue by shaominchen** [vmware/docker-volume-vsphere#1294]
E2E test util verification.ExecCmd may cause the whole e2e test exit due to log.Fatal() call. Instead of fixing log.Fatal(), we should simply remove this util, because it does nothing, but just checking the error and writing a log. We should use ssh.InvokeCommand directly.

@shuklanirdesh82 @ashahi1 @pshahzeb @govint

**Comment by govint** [comment]
When errors happen in the test run we need to know if the issue was with the command executed (syntax or invalid command options for example) or an issue with the service/plugin. Its best if ssh.InvokeCommand() logs the actual command that's was executed - especially when the command fails (at least).

ssh.InvokeCommandLocally() is checking and logging a fatal log if the command failed.

**Comment by shuklanirdesh82** [comment]
It is a trade-off using `log.fatal()`; are we agreeing to get same kind of failures/cascading failure or stop immediately when one of the test fails to invoke supplied command?

When something goes wrong while invoking command incase of remote host is not available (for example); `log.fatal()` makes sense in that scenario otherwise it needs to be change and use `log.Printf()` and let test decide what to do.

**Comment by govint** [comment]
Actually, fatal level logs aren't needed, the test thats calling InvokeCommand will check the error and do a C.Assert which will stop that test anyway with logs.

**Comment by shaominchen** [comment]
I agree with Govindan here. We shouldn't use fatal log in any tests because it will exit the whole test program, which is definitely not we want. As Govinden suggested, returning the error and let the test cases to decide what to do.

**Comment by shuklanirdesh82** [comment]
Thanks @govint & @shaominchen ... I will take care and make a uniform change.

**Comment by shuklanirdesh82** [comment]
E2E test util verification.ExecCmd has been removed so closing this issue not and opening a separate issue to take care about removing `log.fatalf()` after getting massive refactor from #1096.
