### ISSUE TITLE
Reduce the environment difference between CI setup and local nimbus testbed setup

### ISSUE THREAD

**Issue by pshahzeb** [vmware/docker-volume-vsphere#1407]
Recently have seen some issues being hit recently #1395 #1405 #1371 on CI but not on local nimbus testbed we deploy.
Hence we will hit the issue (due to product or test) and not wait till it gets hit in CI. 
This also avoids revisiting the issues, opening new ones.

**Comment by govint** [comment]
We could something like what's collected for a vm-support on ESX. Every possible command  is executed on the host to collect every possible data on it and thats included as part of the logs in a vm-support.

So, in case of a CI error (only), lets run thru all possible docker commands and admin CLI commands and print a log of all those command output. Like, list volumes, then inspect each volume, list containers on each test VM, list volumes, vmgroups, vms in vmgroups, in admin cli. Its not a whole lot but in an error scenario it shows up readily the state of the docker host and ESX.

**Comment by pshahzeb** [comment]
Adding to Govindan's comment here.
Most of the issues are intermittently hit. Possibly a developer doesn't hit them while submitting his/her PR (testing locally on nimbus testbed) and the issue is hit later (may be after a number if runs)
In such cases, gathering all the host info would be useful to get state info and debug the info asap.
//CC @shaominchen @shuklanirdesh82

**Comment by shuklanirdesh82** [comment]
@pshahzeb 

This issue is tracking two different needs. https://github.com/vmware/docker-volume-vsphere/issues/1407#issuecomment-308208148 is suggesting to have log collection improvement where as https://github.com/vmware/docker-volume-vsphere/issues/1407#issue-235634276 asking to reduce the environment difference between CI setup and local nimbus testbed setup.

It is not clear to me what exactly needs to be done to reduce the environment difference between CI setup and local nimbus testbed setup.

It is better to specify the need at https://github.com/vmware/docker-volume-vsphere/issues/1407#issue-235634276 instead of supplying a reference of various issues.

**Comment by shaominchen** [comment]
@shuklanirdesh82 @pshahzeb Can we chat offline and decide if this should be moved or closed?

**Comment by pshahzeb** [comment]
Yes

**Comment by shuklanirdesh82** [comment]
> Can we chat offline and decide if this should be moved or closed?

@pshahzeb Can you atleast add more details at the description part about your request? That will be easier to discuss offline or even we can make call on close or deferred.

**Comment by pshahzeb** [comment]
After offline discussion with @shaominchen @shuklanirdesh82 , we are not able to identify immediate action times as to how we can reduce this gap. Closing this.

@govint This issue filed by you is similar #1042 I guess.
