### ISSUE TITLE
test-all taget (vmlistener_test) hangs due to VM IP reassignment

### ISSUE THREAD

**Issue by venilnoronha** [vmware/docker-volume-vsphere#1462]
When running the `test-all` target locally, I observed that the vmlistener test hanged after a certain point. On doing a preliminary RCA, I found that it was due to an IP reassignment for one of the VMs.

**Comment by shaominchen** [comment]
@venilnoronha Can you please copy/paste the test output here? I guess there should be quite a lot of sleep and then timed out.

**Comment by venilnoronha** [comment]
@shaominchen you're right, it sleeps for a couple of times and then times out. I lost the output, I'll paste it the next time I run into it.

**Comment by shaominchen** [comment]
This happens because VM IP may change after being restarted. The vmlistener tests will kill a VM and then power it on. So this issue may happen in local test run. In CI this won't happen because the VMs in CI setup are all assigned static IP.

VM IP change will not happen frequently, but it's quite annoying when it really happens. So we should fix this issue.

**Comment by shuklanirdesh82** [comment]
not observed such issue, please reopen if you come across again with more details.
