### ISSUE TITLE
[Test] e2e test fails when test VMs are running on different datastore(s). 

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#1507]
While running 'make test-all' on the local testbed, received failures like this: 
```
FAIL: basic_test.go:82: BasicTestSuite.TestVolumeLifecycle

basic_test.go:90:
    c.Assert(accessible, Equals, true, Commentf("Volume %s is not available", s.volName1))
... obtained bool = false
... expected bool = true
... Volume BasicTestSuite.TestVolumeLifecycle_volume_419534 is not available

2017/06/29 00:34:51 START: VolumeAccessTestSuite.TestAccessUpdate
```

It turns out my VMs are on different datastores (some on VSAN, some on local DS) and the tests do not handle it well. 

//CC @shuklanirdesh82 @pshahzeb

**Comment by shuklanirdesh82** [comment]
@shaominchen can you please look into this at your earliest?

**Comment by shaominchen** [comment]
@msterin I guess this failure is not due to your VMs are on different datastores. If you look at the test logic, we are creating the volume on one docker host (VM), and then check the volume availability **on the same VM**. So this logic should not fail if VMs are on different datastores, because the test logic is just related to one single VM. My guess is that the VM might belong to some tenant, in which the default datastore is the not the VM_DS. Can you please confirm is this is the case? I think this is most probably a duplicate to issue #1508.

**Comment by msterin** [comment]
Well, I did not configure any tenants so all config if from the tests, and it passes on CI. So no, I cannot confirm what you say

**Comment by shaominchen** [comment]
Any products may have bugs, same for tests. Our tests are definitely not perfect or even great, but I cannot agree it's more of a distraction. We are automating some extremely complicated end-to-end workflows that cannot be done in unit tests. We have been spending huge number of time to run those test **manually** before cutting releases. With these automated end-to-end tests, we are not suffering those pain anymore - cutting a release will be just a breeze.

I fully understand the frustration here when some tests are failing not because of the change in the PR, but let's just improve it just like we are keeping improving vDVS.

**Comment by msterin** [comment]
Yew, automating is awesome and I am glad we have ever increasing coverage. At the same time, the tests that make it super hard to troubleshoot, and then end up being a test bug, is a problem. In this case the root cause is the original glitch in admin CLI code not returning code, and tests assuming it does. Let's get it fixed asap, but I need help on failing tests to move faster.

**Comment by shaominchen** [comment]
Yes, I completely agree. The reason it's super hard to troubleshoot is because when we saw a test case failure, the failure was sometimes not caused by a test logic error, but caused by some dirty data/setup left over by previous tests. If it's a test logic error, it should still be straightforward to debug.

I will try to address this biggest concern here (as tracked by issue #1508).

**Comment by shaominchen** [comment]
Mark this as duplicate to issue #1508 - I will use the latter to track the issue.
