### ISSUE TITLE
Skylight performance improvement - Investigate accelerating fs_windows implementation

### ISSUE THREAD

**Issue by venilnoronha** [vmware/docker-volume-vsphere#1553]
## Description
The `fs_windows.go` and `device_watcher_windows.go` implementations heavily rely on `PowerShell` scripts to perform `WMI` operations, due to lack of a functional `Go` library to do the same. These `PowerShell` scripts are also embedded within the `.go` files as of today.

The following changes are suggested, in priority order.
1. Replace `PowerShell` scripts with native/third-party `Go` library based implementations.
2. Move `PowerShell` scripts to separate `.ps1` script files (if point 1 isn't immediate).

See #1540 for more details.

## Investigation
The [x/sys/windows](https://godoc.org/golang.org/x/sys/windows) and [syscall_windows](https://golang.org/src/syscall/syscall_windows.go) modules from `Go` don't support device operations. 

Following are a few alternatives to `PowerShell` scripts to implement `fs` functionalities in `Go`.
1. [wmi](https://github.com/a-palchikov/wmi) - a `WMI` wrapper based on Google's legacy [com-and-go](https://code.google.com/archive/p/com-and-go/) package.
2. [go-ole](https://github.com/go-ole/go-ole) based `WMI` queries. StackOverflow discussion [here](https://stackoverflow.com/questions/20365286/query-wmi-from-go).
3. Write a custom wrapper around `kernel32.dll`. See example [here](https://github.com/LukeEuler/bodhi/blob/master/filesystem/filesystem_windows.go).
4. [StackExchange/wmi](https://github.com/StackExchange/wmi) - `IDispatch` based third-party wrapper around `WMI`.
5. [go-wmi](https://github.com/gabriel-samfira/go-wmi) - yet another `IDispatch` based `WMI` wrapper.
6. [walk](https://github.com/lxn/walk) and [win](https://github.com/lxn/win) - multiple `DLL` wrappers.

These libraries/implementations don't fully support device operations as-is, so there is a fair amount of work in getting them to work for our `fs` module.

**Comment by msterin** [comment]
Thanks for the list of API choices. It seems that as long as our PS implementation is not a perf bottleneck (maybe pre-load PS to avoid 1st time perf hit?) we should be fine with PS, but let's keep this Issue around.

**Comment by venilnoronha** [comment]
Since we already have a fully functional plugin built in `Go` (for Linux of course), I would just implement the device handling logic in `C` or `C#` and use it within the `Go` plugin, to maximize reuse.

We could discuss more if required.

**Comment by msterin** [comment]
yep, that's even better. Not sure how C# cooperates with GO though, I suspect it's more challenging that C due to run time complexity. Let's see how PowerShell performs (at the end of a day it hits the same managed .net objects and WMI layer so  maybe it's OK) and go from there.

**Comment by venilnoronha** [comment]
Here are some results obtained from a preliminary profiling of the volume creation workflow.

**Docker Plugin**

The following functions were timed using [`go tool pprof`](https://golang.org/pkg/net/http/pprof/).
- `VMDKOps.create` ~7 seconds
- `VMDKOps.attach` ~2 seconds
- `VMDKOps.detach` ~5 seconds
- `fs.DevAttachWait` ~18 seconds (fully used on `fs.getDiskNum`)
- `fs.Mkfs` ~26 seconds (~18 seconds on `fs.getDiskNum` and ~8 seconds on `PS` format script)

Just starting `PS` takes ~2 seconds. See the full Docker plugin timing graph [here](https://github.com/vmware/docker-volume-vsphere/files/1137343/vmdk-profile.pdf).

**ESX VMDK Ops Service**

Following timings were noted from the esx logs.
- `create` ~7 seconds
- `attach` ~2 seconds
- `detach` ~5 seconds

P.S. The esx host has ~100 `VMDK`s in the `KV` at the moment.

**Comment by msterin** [comment]
Nice work getting the numbers  ! It feels pretty slow... 18 seconds to get a disk number? 
Not a blocker to complete end to end functionality, but does not seem reasonable for anything but demo. 
//CC @pdhamdhere @tusharnt @pshahzeb @shaominchen

**Comment by venilnoronha** [comment]
I'll also try and publish numbers from nimbus. The above ones come from a local ESX.

**Comment by msterin** [comment]
Also it's interesting to compare some numbers (e.g. devAttach) StackExchange implementation. 18 sec feel waaaay too long

**Comment by venilnoronha** [comment]
The numbers have improved significantly after restarting ESX.

**Docker Plugin**
- `VmdkOps.Create` ~2 seconds --- previously ~7 seconds
- `VmdkOps.Attach` ~1 seconds --- previously ~2 seconds
- `VmdkOps.Detach` ~4 seconds --- previously ~5 seconds
- `fs.DevAttachWait` ~2 seconds --- previously ~18 seconds (~2 seconds on `fs.getDiskNum` --- previously ~18 seconds)
- `fs.Mkfs` ~8 seconds --- previously ~26 seconds (~2 seconds on `fs.getDiskNum`--- previously 18 seconds, and ~6 seconds on `PS` format script --- previously ~8 seconds)
- Additionally, Docker now calls the `Get` API since we've implemented it, and it takes ~4 seconds.

Overall, the volume creation workflow is now taking ~21 seconds, which earlier would take ~60 seconds. See the full Docker plugin timing graph [here](https://github.com/vmware/docker-volume-vsphere/files/1157616/new-vmdk-profile.pdf).

**Comment by msterin** [comment]
The rumor has it mount/unmount takes up to 5 sec. We suspect it's due to starting Powershell for each request. 
This Issue is to accelerate it. One of the approaches is to check https://github.com/gorillalabs/go-powershell or similar approach and keep PS around.  We need to get mount to sub-0.5 sec range.

**Comment by venilnoronha** [comment]
Volume creation takes ~12 seconds on a Windows VM on a local testbed.

**Comment by pshahzeb** [comment]
Let's investigate the final action items for this performance enhancement and file separate issue if need be.

**Comment by shaominchen** [comment]
This performance optimization (if possible) will improve user experience significantly. Marking as mustfix for Kubecon release.

**Comment by shuklanirdesh82** [comment]
Profiling has been done again through [`go tool pprof`](https://golang.org/pkg/net/http/pprof/) against the master's code i.e. with  https://github.com/vmware/docker-volume-vsphere/commit/f53b61eda85334d7d83c4e0e374739713e23946c see https://github.com/vmware/docker-volume-vsphere/pull/1991 for more details.

Here are the results obtained from a profiling of the volume creation workflow.

**Docker Plugin**
- `VmdkOps.Create` ~1.56s seconds --- previously ~2 seconds
- `VmdkOps.Attach` ~0.66s seconds --- previously ~1 seconds
- `VmdkOps.Detach` ~0.62s seconds --- previously ~4 seconds
- `fs.DevAttachWait` ~0.03s seconds --- previously ~2 seconds
- `fs.Mkfs` ~0.08s seconds --- previously ~8 seconds 
-  Docker now calls the Get API since we've implemented it, and it takes ~0.35s seconds --- previously ~4 seconds.


Overall, the volume creation workflow is now taking ~11 seconds, which earlier would take ~21 seconds. It seems the performance data is improved through #1991.

See the full Docker plugin timing graph [here](https://github.com/vmware/docker-volume-vsphere/files/1516515/volC.pdf)

/CC @govint @shaominchen @tusharnt 

P.S.: above data is compared with most recent update on this issue https://github.com/vmware/docker-volume-vsphere/issues/1553#issuecomment-316235180

**Comment by govint** [comment]
Great improvement. Well done @shuklanirdesh82 !!
