### ISSUE TITLE
VFile: Reduce vfile log file size and/or reduce number of log files

### ISSUE THREAD

**Issue by govint** [vmware/docker-volume-vsphere#1959]
the vFile logs can grow quiet large and can fill the root partition on a Linux desktop if let unchecked, as below
-rw-r--r-- 1 root      root 100M Sep 12 06:29 vfile-2017-09-12T13-29-48.158.log
-rw-r--r-- 1 root      root 100M Sep 12 06:32 vfile-2017-09-12T13-32-46.970.log
-rw-r--r-- 1 root      root 100M Sep 12 06:34 vfile-2017-09-12T13-34-26.209.log
-rw-r--r-- 1 root      root 100M Sep 12 06:35 vfile-2017-09-12T13-35-55.402.log
-rw-r--r-- 1 root      root 100M Sep 12 06:37 vfile-2017-09-12T13-37-20.429.log
-rw-r--r-- 1 root      root 100M Sep 12 06:38 vfile-2017-09-12T13-38-37.306.log
-rw-r--r-- 1 root      root 100M Sep 12 06:39 vfile-2017-09-12T13-39-48.654.log
-rw-r--r-- 1 root      root 100M Sep 12 06:41 vfile-2017-09-12T13-41-27.220.log
-rw-r--r-- 1 root      root 100M Sep 12 06:42 vfile-2017-09-12T13-42-54.285.log
-rw-r--r-- 1 root      root 100M Sep 12 06:44 vfile-2017-09-12T13-44-44.633.log

Suggest reducing the file size and/or the number of the log files.

**Comment by lipingxue** [comment]
@govint If you still have the log, could you attached the log in this issue? I want to see why the log is flooded.

**Comment by lipingxue** [comment]
Record the offline discussion with Govindan.

For this issue I'm not sure if a repro is needed. IN my case the vfile plugin was experiencing a continuous failure (most likely because I was installing and removing the vdvs plugin, stopping and starting nodes) and was generating a lot of logs. I had to remove the files as the VM hung up. For this issue we could just limit the size of each file and the number of files so that the disk isn't overrun.

**Comment by lipingxue** [comment]
Fix of issue #1964 will solve this problem.

**Comment by luomiao** [comment]
Closed by #1973
