### ISSUE TITLE
Docker Plugin Install failing

### ISSUE THREAD

**Issue by seanhig** [vmware/docker-volume-vsphere#1981]
This started happening just this morning in my test cluster build...

fatal: [swarm-w5]: FAILED! => {"changed": true, "cmd": "docker plugin install --grant-all-permissions --alias vsphere store/vmware/docker-volume-vsphere:latest", "delta": "0:00:00.996201", "end": "2017-11-08 07:42:01.479639", "failed": true, "rc": 1, "start": "2017-11-08 07:42:00.483438", "stderr": "**Error response from daemon: unauthorized: authentication required**", "stderr_lines": ["Error response from daemon: unauthorized: authentication required"], "stdout": "", "stdout_lines": []}

I've also tried to install it manually, and even after logging into dockerhub (which I shouldn't have to do,  I get the same error response from daemon.

At the present time I am unable to install the plugin as per the documentation.

**Comment by shuklanirdesh82** [comment]
@seanhig Sorry to hear that you are facing an issue while installing vDVS plugin. I have tried on my end and I am able to install without any problem (pasting below for your reference)

```
root# docker plugin install --grant-all-permissions --alias vsphere store/vmware/docker-volume-vsphere:latest
latest: Pulling from store/vmware/docker-volume-vsphere
bc8c14d82abc: Download complete 
Digest: sha256:6b81577c0502f537bc8a5ccf3f1599d9f9b7276242d7043d00d04496f312b976
Status: Downloaded newer image for store/vmware/docker-volume-vsphere:latest
Installed plugin store/vmware/docker-volume-vsphere:latest
```

It would be great if you can provide some more logs to help you further. 

1. can you please share docker logs?
2. you may want to check `/var/logs` for the `docker-volume-vsphere.log` and attach with the issue if present.

Can you please clarify one more thing regarding the installation command? Where did you find to use ` store/vmware/docker-volume-vsphere:latest` instead of `vmware/docker-volume-vsphere:latest`?

I would suggest to follow installation instructions mentioned at http://vmware.github.io/docker-volume-vsphere/documentation/install.html#installation-instruction 

Thanks!

**Comment by seanhig** [comment]
Thank you, I found the issue… earlier versions had a different path (as shown in the snippet)

> docker plugin install --grant-all-permissions --alias vsphere store/vmware/docker-volume-vsphere:latest
However, it is now:

> docker plugin install --grant-all-permissions --alias vsphere vmware/docker-volume-vsphere:latest

No more “store/".  I noticed the docs have also been updated.

Must have changed recently, I run those scripts near daily.  Once I made the change it started working again.

Thanks again.

**Comment by shuklanirdesh82** [comment]
> Must have changed recently, I run those scripts near daily.  Once I made the change it started working again.

Thanks @seanhig for confirming quickly! 

Please share your feedback at hatchway@vmware.com and feel free to drop a note for any feature request.

/CC @tusharnt
