### ISSUE TITLE
Check that vm-open-tools are installed

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#207]
Summary:
need to check that either vm-open-tools or vmware-tools  (or just vmci kernel module) are installed

Details:
The code works only if the Linux VM (running Docker) is running under ESX and vm-open-tools or vmware-tools are installed. If they are not, some mystery bugs will be reported.
Plugin GO code needs to check that the vm-open-tools or vmware-tools are installed, and that it is indeed ESX VM (we can see it in BIOS). This will simplify troubleshooting and accelerated solving customer install issues. 

As an alternative, we can write a "check-prerequisites" script thst does all that and (eventually) more.

**Comment by kerneltime** [comment]
There are complications for checking VMCI.
* It can be installed in more than one ways. (open vm tools, VMware tools, built into the kernel)
* It is not always loaded as loadable modules. (Photon)
* Installed does not imply running vmci communication (I have a box where vsock is loaded but does not work since tools are not installed in it's entirety)
At a minimum when we discover communication failures we should log the possible reasons.

**Comment by kerneltime** [comment]
https://github.com/vmware/docker-volume-vsphere/pull/452 will address the logging requirements.
