### ISSUE TITLE
Suppport for SDRS

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#214]
It is fairly widely used and we already heard customers asking for flocker driver supporting SDRS. 
We  wont support it in v1, but I think we need to be clear on the v.next.
Here is an intro http://www.yellow-bricks.com/2012/05/22/an-introduction-to-storage-drs/

**Comment by govint** [comment]
Setting future, v1.next can be deprecated.

**Comment by govint** [comment]
As discussed, this feature is tentatively targeted for Kubecon.

Todo - identify exactly how SDRS applies to container volumes and develop how its leveraged/managed(??) from the container orch. layer.

**Comment by tusharnt** [comment]
Estimate will be decided after initial investigation is completed.

**Comment by govint** [comment]
Estimate 3 for investigation of how SDRS can apply to containers workloads and how well it can integrate with the workflows we have with container volumes.

**Comment by govint** [comment]
Studied SDRS and the actions that it performs and also had a discussion with the SDRS dev. For now at least its not feasible to look at supporting SDRS with docker volumes. Plainly because SDRS works off VMDKs that are associated with VMs and not independent disks that docker volumes are.  Both initial placement and subsequent load balancing based on IO load and capacity usage are all based on monitoring VMs. Storage migrating VMs doesn't make any sense with containers when containers (the workload) can move across VMs. For now at least SDRS isn't going to be able to support container workloads although the multi-tenancy with datastore clusters is a nice feature to leverage for container volumes.
