### ISSUE TITLE
remove command lines usage where API is available

### ISSUE THREAD

**Issue by msterin** [vmware/docker-volume-vsphere#39]
We use 'vmkfstools' to create and delete VMDK (python code), and "mount /umount' to mount a disk (GO code).
We should use si.content.virtualDiskManager (VDM) on python side to create/delete the disk, and syscall.mount sycall.umount to unmount on GO side

**Comment by msterin** [comment]
Partially resolved by #792 . We still used `vmkfstools` in get_vmdk_size_info() since virtualDiskManager does not provide this information.

Current code can (and will) lead to delays in admin 'ls' command since it's happening on each volume, and is serialized over all volume to list. 

We should use kvEsx.get_info() instead of `vmkfstools` in `get_vmdk_size_info()` - this will   use DiskLib directly

**Comment by shaominchen** [comment]
Hi Shahzeb,

Can you validate the scenario suggested by Mark and fix the code appropriately?

**Comment by pshahzeb** [comment]
I tested this scenario by creating 100 volumes each of size 10mb on a vsan datastore through one photon VM.
The admin 'ls' command takes approximately 9 seconds to list all volumes.
```
real	0m 9.68s
user	0m 2.74s
sys	0m 0.00s
```

I replaced the population code in ```get_vmdk_size_info() ``` to make use of ```kvEsx.get_info()``` instead of vmkfstools.
The admin 'ls' command then takes approximately 6 seconds to list all volumes.
```
real	0m 6.05s
user	0m 2.60s
sys	0m 0.00s
```

I tried the ls commands a few times, the delays had very small deviation. Approximately 9 seconds when using ```vmkfstools``` and approximately 6 seconds when using ```kvEsx.get_info()```

**Comment by msterin** [comment]
The diff is not huge  (30% or 3 sec/100 volumes) but if we already have `kvEsx.get_info()` which does the same (does it ? ), then I suggest we drop  `vmfstools` and use `kvEsx.get_info()`

**Comment by pshahzeb** [comment]
Yes ```kvEsx.get_info()``` does the same. We can drop vmkfstools.

**Comment by msterin** [comment]
> Yes kvEsx.get_info() does the same. We can drop vmkfstools.

Great. Please go ahead  and submit a PR for that.
