### ISSUE TITLE
Ship guest docker volume plugin as managed plugin

### ISSUE THREAD

**Issue by pdhamdhere** [vmware/docker-volume-vsphere#886]
Docker managed plugins are out of experimental starting from Docker 1.13. We should consider shipping both vSphere as well as Photon as docker managed plugin.

Reference: https://docs.docker.com/engine/extend/#/developing-a-plugin

The following are PRs related to this feature in docker 1.13 release notes.

Move plugins out of experimental #28226
Add --force on docker plugin remove #25096
Add description in docker plugin ls #25556
Add -f/--format to docker plugin inspect #25990
Add docker plugin create command #28164
Split docker plugin install into two API call /privileges and /pull #28963

REX_Ray seems have implemented the managed plugin system, this blog is a good reference https://blog.codedellemc.com/2017/02/02/deep-dive-docker-1-13-storage-plugins-propagated-mounts/

**Comment by shaominchen** [comment]
Since this feature needs investigation and there are quite some uncertainties, we should start to look into this ASAP to make sure this can be delivered in GA.

**Comment by shaominchen** [comment]
Per offline discussion, Mark will take care of this.

**Comment by msterin** [comment]
Update:
#1006 introduces the managed plugin built. 

Issues still to address: 
* We cannot simply use it from build/CI since it pushes to registry and multiple dev builds/CIs will be stepping on each other. So we need to discuss and adjust build/CI  
* Photon OS seems to have issues - 'mount' consistently fails from managed plugin, but works fine in rpm/deb installation and fine in other distros. So we'd need to keep rpm/deb around for a while 
* minor: we need to remove a mount for /etc from the managed plugin mounts, and instead place config gile in /etc/vmware OR simply use an env to point to it's location (and add env to plugin config.json)

**Comment by msterin** [comment]
This is what we plan to do to address the points in the comment above:
* Devs (or whoever builds of git) will have to use  their own dockerhub accounts. We will try to construct it from DOCKER_HUB_USER env or `whoami`. We will rely on dev having done proper `docker login`, and we will provide help message if the `docker plugin push` fails. W3 will use hardcoded tag (as today) 
 * change to plugin/Makefile (tag->dev) 
 * change to vmdk_plugin Makefile 'make deploy-vm'
* CI build will use cnastorage account. Since CI serializes the build, we will add TAG=ci 
 * change to build scripts
** on release, we will manually push to vmvare/xxx and tag with the release number

//CC @pdhamdhere @shuklanirdesh82
