### ISSUE TITLE
Move volume specific Admin CLI operations to a new "volume" option

### ISSUE THREAD

**Issue by shaominchen** [vmware/docker-volume-vsphere#921]
Currently Admin CLI has the following top-level options: {ls, policy, tenant, set, status}

Among these options, "ls" and "set" are volume specific operations. I think it's clearer and more organized to move those 2 to a new top-level "volume" option, i.e.

vmdkops_admin volume ls...
vmdkops_admin volume set...

This will also avoid confusion when we need to add other new top-level command options.

**Comment by govint** [comment]
This is what we have today and this issue seems to be fixed.

/usr/lib/vmware/vmdkops/bin/vmdkops_admin.py
usage: vmdkops_admin.py [-h] [--output-format OUTPUT_FORMAT]
                        {config,policy,volume,status,vmgroup} ...

vSphere Docker Volume Service admin CLI

optional arguments:
  -h, --help            show this help message and exit
  --output-format OUTPUT_FORMAT
                        Specify output format. Supported format : xml. Default
                        one is plaintext

Manage VMDK-based Volumes for Docker:

  {config,policy,volume,status,vmgroup}
                        action
    config              Init and manage Config DB to enable quotas and access
                        control [EXPERIMENTAL]
    policy              Configure and display storage policy information
    volume              Manipulate volumes
    status              Show the status of the vmdk_ops service
    vmgroup             Administer and monitor volume access control
