### ISSUE TITLE
Does the new "tenant" feature span esxi hosts?

### ISSUE THREAD

**Issue by matt-deboer** [vmware/docker-volume-vsphere#952]
In our previously used version of the driver (0.9.x) we were able to mount a given volume from any vm on any esxi host attached to the datastore (not simultaneously, of course, but if a given containerized app was launched on another vm--on another esxi host--in the same cluster, it would be able to mount the previously created volume).

Is there a way to achieve this functionality with the current setup?

**Comment by pdhamdhere** [comment]
Hey @matt-deboer We had a [regression](#193) in latest release which impacts visibility of Docker Volumes on shared datastore across multiple ESX Hosts.

This is fixed in latest [patch release](https://github.com/vmware/docker-volume-vsphere/releases/tag/0.11.2).
For upgrades, please see instructions [here](https://github.com/vmware/docker-volume-vsphere/blob/master/docs/misc/UpgradeFrom_Pre0.11.1.md).
[Upgrade script](https://github.com/vmware/docker-volume-vsphere/pull/951) to patch DB and move docker volumes to appropriate directory will be available soon.
